name: Airflow CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pandas
          pip install sqlalchemy
          pip install psycopg2-binary

      - name: Validate Config Script
        run: |
          python scripts/read_config.py